In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

In [13]:
# Load the diabetes dataset
diabetes = datasets.load_diabetes()
diabetes_X_scale = preprocessing.scale(diabetes.data)
print(diabetes.data.shape)
print(diabetes.target.shape)
print(diabetes_X_scale.shape)

(442, 10)
(442,)
(442, 10)


In [11]:
np.apply_along_axis(np.mean, 0, diabetes.data)

array([-3.63962254e-16,  1.30991246e-16, -8.01395149e-16,  1.28981793e-16,
       -9.04254047e-17,  1.30112110e-16, -4.56397112e-16,  3.86317424e-16,
       -3.84810333e-16, -3.39848813e-16])

In [12]:
np.apply_along_axis(np.std, 0, diabetes.data)

array([0.04756515, 0.04756515, 0.04756515, 0.04756515, 0.04756515,
       0.04756515, 0.04756515, 0.04756515, 0.04756515, 0.04756515])

In [5]:
np.apply_along_axis(np.mean, 0, diabetes_X_scale)

array([-3.21512550e-17, -8.03781375e-17,  4.82268825e-17,  5.62646963e-17,
       -4.82268825e-17, -5.62646963e-17,  4.42079756e-17,  2.25058785e-16,
       -4.42079756e-17,  3.21512550e-17])

In [10]:
np.apply_along_axis(np.std, 0, diabetes_X_scale)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
class Foo:
    def fit(x): 
        pass
    
    def transform(x):
        return x

In [30]:
sc = preprocessing.StandardScaler()
sc.fit(np.random.random((10,2)))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [31]:
pipe = Pipeline(steps=[
    ('scale', sc),
    ('foo', Foo),
    ('linear', linear_model.LinearRegression)
])
pipe

Pipeline(memory=None,
     steps=[('scale', StandardScaler(copy=True, with_mean=True, with_std=True)), ('foo', <class '__main__.Foo'>), ('linear', <class 'sklearn.linear_model.base.LinearRegression'>)])

In [25]:
pipe.fit

<bound method Pipeline.fit of Pipeline(memory=None,
     steps=[('scale', <class 'sklearn.preprocessing.data.StandardScaler'>), ('linear', <class 'sklearn.linear_model.base.LinearRegression'>)])>