In [8]:
import numpy as np

In [1]:
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest

In [16]:
head = lambda x, k = 6: x[:k]

In [2]:
iris = load_iris()

X, y = iris.data, iris.target

In [10]:
X = np.random.randn(80,100)
y = np.random.randn(80)
tmp = SelectKBest(k=1).fit_transform(X, y)
tmp.shape

/local_data/env-py3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:109: RuntimeWarning: invalid value encountered in true_divide
  msw = sswn / float(dfwn)


(80, 1)

In [12]:
# This dataset is way too high-dimensional. Better do PCA:
pca = PCA(n_components=2)

# Maybe some original features where good, too?
selection = SelectKBest(k=1)

In [13]:
# Build estimator from PCA and Univariate selection:
combined_features = FeatureUnion([("pca", pca), ("univ_select", selection)])

In [14]:
# Use combined features to transform dataset:
X_features = combined_features.fit(X, y).transform(X)

/local_data/env-py3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:109: RuntimeWarning: invalid value encountered in true_divide
  msw = sswn / float(dfwn)


In [18]:
head(pca.transform(X))

array([[-2.59565406, -3.53008672],
       [-3.19329912,  0.59338054],
       [ 0.46938443,  2.81752141],
       [ 2.21686161, -0.86482145],
       [-4.02026411,  1.84846276],
       [ 5.78015733,  1.38066292]])

In [19]:
head(selection.transform(X))

array([[ 0.89935586],
       [-0.59497338],
       [-2.60068628],
       [-1.30243601],
       [ 1.11043387],
       [ 1.44039194]])

In [20]:
head(X_features)

array([[-2.59565406, -3.53008672,  0.89935586],
       [-3.19329912,  0.59338054, -0.59497338],
       [ 0.46938443,  2.81752141, -2.60068628],
       [ 2.21686161, -0.86482145, -1.30243601],
       [-4.02026411,  1.84846276,  1.11043387],
       [ 5.78015733,  1.38066292,  1.44039194]])

----

[sklearn.feature_selection.SelectKBest](http://scikit-learn.org/stable/auto_examples/plot_feature_stacker.html#sphx-glr-auto-examples-plot-feature-stacker-py)

In [ ]:
# Author: Andreas Mueller <amueller@ais.uni-bonn.de>
#
# License: BSD 3 clause

from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest

iris = load_iris()

X, y = iris.data, iris.target

# This dataset is way too high-dimensional. Better do PCA:
pca = PCA(n_components=2)

# Maybe some original features where good, too?
selection = SelectKBest(k=1)

# Build estimator from PCA and Univariate selection:

combined_features = FeatureUnion([("pca", pca), ("univ_select", selection)])

# Use combined features to transform dataset:
X_features = combined_features.fit(X, y).transform(X)

svm = SVC(kernel="linear")

# Do grid search over k, n_components and C:

pipeline = Pipeline([("features", combined_features), ("svm", svm)])

param_grid = dict(features__pca__n_components=[1, 2, 3],
                  features__univ_select__k=[1, 2],
                  svm__C=[0.1, 1, 10])

grid_search = GridSearchCV(pipeline, param_grid=param_grid, verbose=10)
grid_search.fit(X, y)
print(grid_search.best_estimator_)