In [2]:
import numpy as np

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline

In [3]:
class Foo1(BaseEstimator, TransformerMixin):
    
    def __init__(self):
        self.k = 2
        
    def fit(self, x, y=None):
        return self

    def transform(self, x):
        return self.k * x
    
class Foo2(BaseEstimator, TransformerMixin):
    
    def __init__(self, k):
        self.k = k
        
    def fit(self, x, y=None):
        return self

    def transform(self, x):
        return self.k * x        

In [4]:
pipeline = Pipeline([
    ('foo1', Foo1()),
    ('foo2', Foo2(3))
])

In [5]:
x = np.reshape(np.arange(6), (3,2))

In [6]:
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
pipeline.fit(x)

Pipeline(memory=None, steps=[('foo1', Foo1()), ('foo2', Foo2(k=3))])

In [8]:
pipeline.transform(x)

array([[ 0,  6],
       [12, 18],
       [24, 30]])

In [9]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [10]:
pipeline.fit(x)

Pipeline(memory=None, steps=[('foo1', Foo1()), ('foo2', Foo2(k=3))])

In [11]:
pipeline.transform(x)

array([ 0,  6, 12, 18, 24, 30])