# About [scikit-cuda](http://scikit-cuda.readthedocs.io/en/latest/index.html)

scikit-cuda provides Python interfaces to many of the functions in the CUDA device/runtime, **CUBLAS, CUFFT, and CUSOLVER libraries distributed as part of NVIDIA’s CUDA Programming Toolkit**, as well as interfaces to select functions in the CULA Dense Toolkit. Both low-level wrapper functions similar to their C counterparts and high-level functions comparable to those in **NumPy and Scipy** are provided.

# skcuda.linalg.norm

In [1]:
import pycuda.autoinit
import pycuda.gpuarray as gpuarray
import numpy as np
import skcuda.linalg as linalg

In [2]:
linalg.init()
x = np.asarray(np.random.rand(4, 4), np.float32)
x_gpu = gpuarray.to_gpu(x)
nrm = linalg.norm(x_gpu)
np.allclose(nrm, np.linalg.norm(x))
True
x_gpu = gpuarray.to_gpu(np.array([3+4j, 12-84j]))
linalg.norm(x_gpu)

85.0

# skcuda.linalg.mdot

In [46]:
import pycuda.gpuarray as gpuarray
import pycuda.autoinit
import numpy as np
import skcuda.linalg as linalg
linalg.init()
a = np.asarray(np.random.rand(4, 2), np.float32)
b = np.asarray(np.random.rand(2, 2), np.float32)
c = np.asarray(np.random.rand(2, 2), np.float32)
a_gpu = gpuarray.to_gpu(a)
b_gpu = gpuarray.to_gpu(b)
c_gpu = gpuarray.to_gpu(c)
d_gpu = linalg.mdot(a_gpu, b_gpu, c_gpu)
np.allclose(np.dot(a, np.dot(b, c)), d_gpu.get())

True

In [47]:
d_gpu = linalg.mdot(a_gpu, b_gpu, c_gpu)

LogicError: device_allocation::free failed: invalid resource handle

In [18]:
a = np.asarray(np.random.rand(4, 2), np.float32)
print(a)

[[0.8777161  0.1943787 ]
 [0.74674344 0.89085466]
 [0.15782101 0.41716105]
 [0.6390914  0.9447496 ]]


In [27]:
A = np.array([[1, 2, 3], [4, 5, 6]], np.float32)
B = np.array([1, 1, 1], np.float32).reshape(-1, 1)
print(A)
print(B)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1.]
 [1.]
 [1.]]


In [30]:
A_gpu = gpuarray.to_gpu(A)
B_gpu = gpuarray.to_gpu(B)
AB_gpu = linalg.mdot(A_gpu, B_gpu)
np.allclose(np.matmul(A, B), AB_gpu.get())

True

In [28]:
np.matmul(A, B)

array([[ 6.],
       [15.]], dtype=float32)

In [29]:
np.dot(A, B)

array([[ 6.],
       [15.]], dtype=float32)

In [31]:
AB_gpu.get()

array([[ 6.],
       [15.]], dtype=float32)